[package]
name = "gaussrf"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32.4"
rand = "0.8.5"
rand_distr = "0.4.3"
